"use client";

import { useState } from "react";
import {
  FileText,
  Target,
  Users,
  Palette,
  Package,
  Clock,
  DollarSign,
  Link2,
  StickyNote,
  Copy,
  Check,
  Download,
  RotateCcw,
} from "lucide-react";
import type { GeneratedBrief, BriefFormData } from "@/types/brief";

interface GeneratedBriefViewProps {
  brief: GeneratedBrief;
  formData: BriefFormData;
  onReset: () => void;
}

interface SectionProps {
  icon: React.ReactNode;
  title: string;
  children: React.ReactNode;
}

function Section({ icon, title, children }: SectionProps) {
  return (
    <div
      className="rounded-xl p-6"
      style={{
        background: "var(--surface-elevated)",
        border: "1px solid var(--border)",
      }}
    >
      <div className="flex items-center gap-3 mb-4">
        <div
          className="w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0"
          style={{ background: "rgba(201, 169, 110, 0.1)" }}
        >
          <span style={{ color: "var(--accent)" }}>{icon}</span>
        </div>
        <h3
          className="text-xs font-bold tracking-widest uppercase"
          style={{ color: "var(--accent)" }}
        >
          {title}
        </h3>
      </div>
      {children}
    </div>
  );
}

export function GeneratedBriefView({ brief, formData, onReset }: GeneratedBriefViewProps) {
  const [copied, setCopied] = useState(false);

  const formatDate = (iso: string) => {
    return new Date(iso).toLocaleDateString("en-US", {
      day: "numeric",
      month: "long",
      year: "numeric",
    });
  };

  const buildCopyText = () => {
    const lines = [
      `PROJECT BRIEF — ${formData.projectName || "Untitled Project"}`,
      `Prepared for: ${formData.companyName || formData.clientName}`,
      `Generated: ${formatDate(brief.generatedAt)}`,
      ``,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      ``,
      `PROJECT OVERVIEW`,
      brief.projectOverview,
      ``,
      `OBJECTIVES`,
      ...brief.objectives.map((o) => `• ${o}`),
      ``,
      `TARGET AUDIENCE`,
      brief.targetAudience,
      ``,
      `CREATIVE DIRECTION`,
      brief.creativeDirection,
      ``,
      `DELIVERABLES`,
      ...brief.deliverables.map((d) => `• ${d}`),
      ``,
      `TIMELINE`,
      brief.timeline,
      ``,
      `BUDGET`,
      brief.budget,
      ``,
      ...(brief.references.length > 0
        ? [
            `REFERENCES`,
            ...brief.references.map((r) => `• ${r.label}: ${r.url}${r.notes ? ` — ${r.notes}` : ""}`),
            ``,
          ]
        : []),
      `TECHNICAL REQUIREMENTS`,
      brief.technicalRequirements,
      ``,
      `ADDITIONAL NOTES`,
      brief.notes,
      ``,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      `Generated by Briefly — Studio 858`,
    ];
    return lines.join("\n");
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(buildCopyText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const text = buildCopyText();
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `brief-${(formData.projectName || "project").toLowerCase().replace(/\s+/g, "-")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="animate-fade-in">
      {/* Header */}
      <div
        className="rounded-2xl p-8 mb-6 relative overflow-hidden"
        style={{
          background: "linear-gradient(135deg, var(--surface-elevated) 0%, var(--muted) 100%)",
          border: "1px solid var(--border)",
        }}
      >
        {/* Decorative line */}
        <div
          className="absolute top-0 left-0 right-0 h-0.5"
          style={{
            background: "linear-gradient(90deg, transparent, var(--accent), transparent)",
          }}
        />

        <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
          <div>
            <p
              className="text-xs font-bold tracking-widest uppercase mb-2"
              style={{ color: "var(--accent)" }}
            >
              Project Brief
            </p>
            <h1
              className="text-3xl font-bold tracking-tight"
              style={{ color: "var(--foreground)", letterSpacing: "-0.03em" }}
            >
              {formData.projectName || "Untitled Project"}
            </h1>
            {(formData.companyName || formData.clientName) && (
              <p className="text-sm mt-1.5" style={{ color: "var(--muted-foreground)" }}>
                {formData.companyName || formData.clientName}
                {formData.clientEmail && (
                  <span> · {formData.clientEmail}</span>
                )}
              </p>
            )}
            <p className="text-xs mt-3" style={{ color: "var(--muted-foreground)" }}>
              Generated {formatDate(brief.generatedAt)}
            </p>
          </div>

          {/* Actions */}
          <div className="flex gap-2 flex-shrink-0">
            <button
              onClick={handleCopy}
              className="flex items-center gap-2 px-4 py-2.5 rounded-lg text-xs font-medium transition-all duration-200"
              style={{
                background: "var(--surface)",
                border: "1px solid var(--border)",
                color: copied ? "var(--accent)" : "var(--muted-foreground)",
              }}
              onMouseEnter={(e) =>
                !copied && (e.currentTarget.style.borderColor = "var(--accent)")
              }
              onMouseLeave={(e) =>
                !copied && (e.currentTarget.style.borderColor = "var(--border)")
              }
            >
              {copied ? <Check size={13} /> : <Copy size={13} />}
              {copied ? "Copied!" : "Copy"}
            </button>
            <button
              onClick={handleDownload}
              className="flex items-center gap-2 px-4 py-2.5 rounded-lg text-xs font-medium transition-all duration-200"
              style={{
                background: "var(--surface)",
                border: "1px solid var(--border)",
                color: "var(--muted-foreground)",
              }}
              onMouseEnter={(e) =>
                (e.currentTarget.style.borderColor = "var(--accent)")
              }
              onMouseLeave={(e) =>
                (e.currentTarget.style.borderColor = "var(--border)")
              }
            >
              <Download size={13} />
              Download
            </button>
          </div>
        </div>
      </div>

      {/* Brief Sections */}
      <div className="grid grid-cols-1 gap-4">
        <Section icon={<FileText size={16} />} title="Project Overview">
          <p className="text-sm leading-relaxed" style={{ color: "var(--foreground)" }}>
            {brief.projectOverview}
          </p>
        </Section>

        <Section icon={<Target size={16} />} title="Objectives">
          <ul className="flex flex-col gap-2">
            {brief.objectives.map((obj, i) => (
              <li key={i} className="flex items-start gap-3">
                <span
                  className="w-5 h-5 rounded flex items-center justify-center text-[10px] font-bold flex-shrink-0 mt-0.5"
                  style={{
                    background: "rgba(201, 169, 110, 0.15)",
                    color: "var(--accent)",
                  }}
                >
                  {i + 1}
                </span>
                <p className="text-sm leading-relaxed" style={{ color: "var(--foreground)" }}>
                  {obj}
                </p>
              </li>
            ))}
          </ul>
        </Section>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <Section icon={<Users size={16} />} title="Target Audience">
            <p className="text-sm leading-relaxed" style={{ color: "var(--foreground)" }}>
              {brief.targetAudience}
            </p>
          </Section>

          <Section icon={<Palette size={16} />} title="Creative Direction">
            <p className="text-sm leading-relaxed" style={{ color: "var(--foreground)" }}>
              {brief.creativeDirection}
            </p>
          </Section>
        </div>

        <Section icon={<Package size={16} />} title="Deliverables">
          <ul className="flex flex-col gap-2">
            {brief.deliverables.map((d, i) => (
              <li key={i} className="flex items-start gap-2">
                <span
                  className="w-1.5 h-1.5 rounded-full flex-shrink-0 mt-2"
                  style={{ background: "var(--accent)" }}
                />
                <p className="text-sm leading-relaxed" style={{ color: "var(--foreground)" }}>
                  {d}
                </p>
              </li>
            ))}
          </ul>
        </Section>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <Section icon={<Clock size={16} />} title="Timeline">
            <p className="text-sm leading-relaxed" style={{ color: "var(--foreground)" }}>
              {brief.timeline}
            </p>
          </Section>

          <Section icon={<DollarSign size={16} />} title="Budget">
            <p className="text-sm leading-relaxed" style={{ color: "var(--foreground)" }}>
              {brief.budget}
            </p>
          </Section>
        </div>

        {brief.references.length > 0 && (
          <Section icon={<Link2 size={16} />} title="References">
            <div className="flex flex-col gap-3">
              {brief.references.map((ref) => (
                <div key={ref.id} className="flex flex-col gap-0.5">
                  <a
                    href={ref.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-sm font-medium transition-colors hover:underline"
                    style={{ color: "var(--accent)" }}
                  >
                    {ref.label || ref.url}
                  </a>
                  {ref.notes && (
                    <p className="text-xs" style={{ color: "var(--muted-foreground)" }}>
                      {ref.notes}
                    </p>
                  )}
                </div>
              ))}
            </div>
          </Section>
        )}

        <Section icon={<FileText size={16} />} title="Technical Requirements">
          <p className="text-sm leading-relaxed" style={{ color: "var(--foreground)" }}>
            {brief.technicalRequirements}
          </p>
        </Section>

        {brief.notes && brief.notes !== "No additional notes provided." && (
          <Section icon={<StickyNote size={16} />} title="Additional Notes">
            <p className="text-sm leading-relaxed" style={{ color: "var(--foreground)" }}>
              {brief.notes}
            </p>
          </Section>
        )}

        {/* Uploaded files summary */}
        {(formData.uploadedFiles.length > 0 || formData.existingBrief.length > 0) && (
          <Section icon={<FileText size={16} />} title="Attached Files">
            <div className="flex flex-col gap-2">
              {[...formData.existingBrief, ...formData.uploadedFiles].map((file) => (
                <div key={file.id} className="flex items-center gap-2">
                  <span
                    className="w-1.5 h-1.5 rounded-full flex-shrink-0"
                    style={{ background: "var(--accent)" }}
                  />
                  <p className="text-sm" style={{ color: "var(--foreground)" }}>
                    {file.name}
                  </p>
                  <span className="text-xs" style={{ color: "var(--muted-foreground)" }}>
                    ({(file.size / 1024).toFixed(0)} KB)
                  </span>
                </div>
              ))}
            </div>
          </Section>
        )}
      </div>

      {/* Footer CTA */}
      <div className="mt-8 flex flex-col sm:flex-row gap-3 justify-between items-center">
        <button
          onClick={onReset}
          className="flex items-center gap-2 px-5 py-3 rounded-xl text-sm font-medium transition-all duration-200"
          style={{
            background: "var(--surface)",
            border: "1px solid var(--border)",
            color: "var(--muted-foreground)",
          }}
          onMouseEnter={(e) =>
            (e.currentTarget.style.color = "var(--foreground)")
          }
          onMouseLeave={(e) =>
            (e.currentTarget.style.color = "var(--muted-foreground)")
          }
        >
          <RotateCcw size={14} />
          Start a new brief
        </button>

        <div className="flex gap-3">
          <button
            onClick={handleCopy}
            className="flex items-center gap-2 px-5 py-3 rounded-xl text-sm font-medium transition-all duration-200"
            style={{
              background: "var(--surface)",
              border: "1px solid var(--border)",
              color: copied ? "var(--accent)" : "var(--foreground)",
            }}
          >
            {copied ? <Check size={14} /> : <Copy size={14} />}
            {copied ? "Copied to clipboard!" : "Copy brief"}
          </button>
          <button
            onClick={handleDownload}
            className="flex items-center gap-2 px-6 py-3 rounded-xl text-sm font-bold transition-all duration-200"
            style={{
              background: "var(--accent)",
              color: "var(--background)",
            }}
            onMouseEnter={(e) =>
              (e.currentTarget.style.opacity = "0.9")
            }
            onMouseLeave={(e) =>
              (e.currentTarget.style.opacity = "1")
            }
          >
            <Download size={14} />
            Download Brief
          </button>
        </div>
      </div>
    </div>
  );
}
