"use client";

import { useState } from "react";
import {
  FileText,
  Target,
  Users,
  Palette,
  Package,
  Clock,
  DollarSign,
  Link2,
  StickyNote,
  Copy,
  Check,
  Download,
  RotateCcw,
} from "lucide-react";
import type { GeneratedBrief, BriefFormData } from "@/types/brief";

interface GeneratedBriefViewProps {
  brief: GeneratedBrief;
  formData: BriefFormData;
  onReset: () => void;
}

interface SectionProps {
  icon: React.ReactNode;
  title: string;
  children: React.ReactNode;
  accentBar?: boolean;
}

function Section({ icon, title, children, accentBar = false }: SectionProps) {
  return (
    <div
      style={{
        background: "var(--surface-elevated)",
        border: "1px solid var(--border)",
        borderRadius: "4px",
        padding: "28px 32px",
        position: "relative",
        overflow: "hidden",
      }}
    >
      {accentBar && (
        <div
          style={{
            position: "absolute",
            top: 0,
            left: 0,
            width: "2px",
            height: "100%",
            background: "var(--accent)",
          }}
        />
      )}
      <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "16px" }}>
        <span style={{ color: "var(--accent)", opacity: 0.8, flexShrink: 0 }}>{icon}</span>
        <h3
          style={{
            fontSize: "9px",
            fontWeight: 700,
            letterSpacing: "0.18em",
            textTransform: "uppercase",
            color: "var(--muted-foreground)",
            fontFamily: "var(--font-dm-sans), sans-serif",
          }}
        >
          {title}
        </h3>
      </div>
      {children}
    </div>
  );
}

export function GeneratedBriefView({ brief, formData, onReset }: GeneratedBriefViewProps) {
  const [copied, setCopied] = useState(false);

  const formatDate = (iso: string) => {
    return new Date(iso).toLocaleDateString("en-US", {
      day: "numeric",
      month: "long",
      year: "numeric",
    });
  };

  const buildCopyText = () => {
    const lines = [
      `PROJECT BRIEF — ${formData.projectName || "Untitled Project"}`,
      `Prepared for: ${formData.companyName || formData.clientName}`,
      `Generated: ${formatDate(brief.generatedAt)}`,
      ``,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      ``,
      `PROJECT OVERVIEW`,
      brief.projectOverview,
      ``,
      `OBJECTIVES`,
      ...brief.objectives.map((o) => `• ${o}`),
      ``,
      `TARGET AUDIENCE`,
      brief.targetAudience,
      ``,
      `CREATIVE DIRECTION`,
      brief.creativeDirection,
      ``,
      `DELIVERABLES`,
      ...brief.deliverables.map((d) => `• ${d}`),
      ``,
      `TIMELINE`,
      brief.timeline,
      ``,
      `BUDGET`,
      brief.budget,
      ``,
      ...(brief.references.length > 0
        ? [
            `REFERENCES`,
            ...brief.references.map((r) => `• ${r.label}: ${r.url}${r.notes ? ` — ${r.notes}` : ""}`),
            ``,
          ]
        : []),
      `TECHNICAL REQUIREMENTS`,
      brief.technicalRequirements,
      ``,
      `ADDITIONAL NOTES`,
      brief.notes,
      ``,
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
      `Generated by Briefly — Studio 858`,
    ];
    return lines.join("\n");
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(buildCopyText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const text = buildCopyText();
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `brief-${(formData.projectName || "project").toLowerCase().replace(/\s+/g, "-")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const bodyText: React.CSSProperties = {
    fontSize: "14px",
    lineHeight: 1.75,
    color: "var(--foreground)",
    opacity: 0.88,
  };

  return (
    <div className="animate-fade-in">
      {/* Hero header */}
      <div
        style={{
          marginBottom: "40px",
          paddingBottom: "40px",
          borderBottom: "1px solid var(--border)",
        }}
      >
        <p
          style={{
            fontSize: "10px",
            fontWeight: 600,
            letterSpacing: "0.22em",
            textTransform: "uppercase",
            color: "var(--accent)",
            fontFamily: "var(--font-dm-sans), sans-serif",
            marginBottom: "16px",
          }}
        >
          — Project Brief
        </p>

        <h1
          style={{
            fontFamily: "var(--font-cormorant), Georgia, serif",
            fontSize: "clamp(36px, 7vw, 60px)",
            fontWeight: 600,
            letterSpacing: "-0.02em",
            lineHeight: 1.05,
            color: "var(--foreground)",
            marginBottom: "16px",
          }}
        >
          {formData.projectName || "Untitled Project"}
        </h1>

        <div
          style={{
            display: "flex",
            flexWrap: "wrap",
            alignItems: "center",
            gap: "16px",
            justifyContent: "space-between",
          }}
        >
          <div>
            {(formData.companyName || formData.clientName) && (
              <p style={{ fontSize: "13px", color: "var(--muted-foreground)", marginBottom: "4px" }}>
                {formData.companyName || formData.clientName}
                {formData.clientEmail && (
                  <span style={{ opacity: 0.6 }}> · {formData.clientEmail}</span>
                )}
              </p>
            )}
            <p
              style={{
                fontSize: "11px",
                color: "var(--muted-foreground)",
                letterSpacing: "0.04em",
                opacity: 0.6,
                fontFamily: "var(--font-mono), monospace",
              }}
            >
              Generated {formatDate(brief.generatedAt)}
            </p>
          </div>

          {/* Actions */}
          <div style={{ display: "flex", gap: "8px", flexShrink: 0 }}>
            <button
              onClick={handleCopy}
              style={{
                display: "flex",
                alignItems: "center",
                gap: "6px",
                padding: "10px 18px",
                background: "transparent",
                border: "1px solid var(--border)",
                borderRadius: "3px",
                color: copied ? "var(--accent)" : "var(--muted-foreground)",
                fontSize: "10px",
                fontWeight: 600,
                letterSpacing: "0.1em",
                textTransform: "uppercase",
                cursor: "pointer",
                transition: "all 0.2s ease",
                fontFamily: "var(--font-dm-sans), sans-serif",
              }}
              onMouseEnter={(e) => {
                if (!copied) e.currentTarget.style.borderColor = "var(--accent)";
              }}
              onMouseLeave={(e) => {
                if (!copied) e.currentTarget.style.borderColor = "var(--border)";
              }}
            >
              {copied ? <Check size={12} /> : <Copy size={12} />}
              {copied ? "Copied!" : "Copy"}
            </button>
            <button
              onClick={handleDownload}
              style={{
                display: "flex",
                alignItems: "center",
                gap: "6px",
                padding: "10px 18px",
                background: "transparent",
                border: "1px solid var(--border)",
                borderRadius: "3px",
                color: "var(--muted-foreground)",
                fontSize: "10px",
                fontWeight: 600,
                letterSpacing: "0.1em",
                textTransform: "uppercase",
                cursor: "pointer",
                transition: "all 0.2s ease",
                fontFamily: "var(--font-dm-sans), sans-serif",
              }}
              onMouseEnter={(e) => (e.currentTarget.style.borderColor = "var(--accent)")}
              onMouseLeave={(e) => (e.currentTarget.style.borderColor = "var(--border)")}
            >
              <Download size={12} />
              Download
            </button>
          </div>
        </div>
      </div>

      {/* Brief Sections */}
      <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
        <Section icon={<FileText size={14} />} title="Project Overview" accentBar>
          <p style={bodyText}>{brief.projectOverview}</p>
        </Section>

        <Section icon={<Target size={14} />} title="Objectives">
          <ul style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
            {brief.objectives.map((obj, i) => (
              <li key={i} style={{ display: "flex", alignItems: "flex-start", gap: "12px" }}>
                <span
                  style={{
                    width: "20px",
                    height: "20px",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    fontSize: "10px",
                    fontWeight: 700,
                    flexShrink: 0,
                    marginTop: "2px",
                    color: "var(--accent)",
                    background: "rgba(196, 160, 107, 0.1)",
                    borderRadius: "2px",
                    fontFamily: "var(--font-mono), monospace",
                  }}
                >
                  {i + 1}
                </span>
                <p style={bodyText}>{obj}</p>
              </li>
            ))}
          </ul>
        </Section>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
            gap: "12px",
          }}
        >
          <Section icon={<Users size={14} />} title="Target Audience">
            <p style={bodyText}>{brief.targetAudience}</p>
          </Section>

          <Section icon={<Palette size={14} />} title="Creative Direction">
            <p style={bodyText}>{brief.creativeDirection}</p>
          </Section>
        </div>

        <Section icon={<Package size={14} />} title="Deliverables">
          <ul style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
            {brief.deliverables.map((d, i) => (
              <li key={i} style={{ display: "flex", alignItems: "flex-start", gap: "10px" }}>
                <span
                  style={{
                    width: "4px",
                    height: "4px",
                    borderRadius: "50%",
                    background: "var(--accent)",
                    flexShrink: 0,
                    marginTop: "9px",
                  }}
                />
                <p style={bodyText}>{d}</p>
              </li>
            ))}
          </ul>
        </Section>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
            gap: "12px",
          }}
        >
          <Section icon={<Clock size={14} />} title="Timeline">
            <p style={bodyText}>{brief.timeline}</p>
          </Section>

          <Section icon={<DollarSign size={14} />} title="Budget">
            <p style={bodyText}>{brief.budget}</p>
          </Section>
        </div>

        {brief.references.length > 0 && (
          <Section icon={<Link2 size={14} />} title="References">
            <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
              {brief.references.map((ref) => (
                <div key={ref.id} style={{ display: "flex", flexDirection: "column", gap: "3px" }}>
                  <a
                    href={ref.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    style={{
                      fontSize: "14px",
                      fontWeight: 500,
                      color: "var(--accent)",
                      textDecoration: "none",
                      transition: "opacity 0.2s ease",
                    }}
                    onMouseEnter={(e) => (e.currentTarget.style.opacity = "0.75")}
                    onMouseLeave={(e) => (e.currentTarget.style.opacity = "1")}
                  >
                    {ref.label || ref.url}
                  </a>
                  {ref.notes && (
                    <p style={{ fontSize: "12px", color: "var(--muted-foreground)" }}>{ref.notes}</p>
                  )}
                </div>
              ))}
            </div>
          </Section>
        )}

        <Section icon={<FileText size={14} />} title="Technical Requirements">
          <p style={bodyText}>{brief.technicalRequirements}</p>
        </Section>

        {brief.notes && brief.notes !== "No additional notes provided." && (
          <Section icon={<StickyNote size={14} />} title="Additional Notes">
            <p style={bodyText}>{brief.notes}</p>
          </Section>
        )}

        {(formData.uploadedFiles.length > 0 || formData.existingBrief.length > 0) && (
          <Section icon={<FileText size={14} />} title="Attached Files">
            <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
              {[...formData.existingBrief, ...formData.uploadedFiles].map((file) => (
                <div key={file.id} style={{ display: "flex", alignItems: "center", gap: "10px" }}>
                  <span
                    style={{
                      width: "4px",
                      height: "4px",
                      borderRadius: "50%",
                      background: "var(--accent)",
                      flexShrink: 0,
                    }}
                  />
                  <p style={{ fontSize: "14px", color: "var(--foreground)" }}>{file.name}</p>
                  <span
                    style={{
                      fontSize: "11px",
                      color: "var(--muted-foreground)",
                      fontFamily: "var(--font-mono), monospace",
                    }}
                  >
                    ({(file.size / 1024).toFixed(0)} KB)
                  </span>
                </div>
              ))}
            </div>
          </Section>
        )}
      </div>

      {/* Footer CTA */}
      <div
        style={{
          marginTop: "48px",
          paddingTop: "32px",
          borderTop: "1px solid var(--border)",
          display: "flex",
          flexWrap: "wrap",
          gap: "12px",
          justifyContent: "space-between",
          alignItems: "center",
        }}
      >
        <button
          onClick={onReset}
          style={{
            display: "flex",
            alignItems: "center",
            gap: "8px",
            padding: "13px 22px",
            background: "transparent",
            border: "1px solid var(--border)",
            borderRadius: "3px",
            color: "var(--muted-foreground)",
            fontSize: "11px",
            fontWeight: 600,
            letterSpacing: "0.1em",
            textTransform: "uppercase",
            cursor: "pointer",
            transition: "all 0.2s ease",
            fontFamily: "var(--font-dm-sans), sans-serif",
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.borderColor = "var(--muted-foreground)";
            e.currentTarget.style.color = "var(--foreground)";
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.borderColor = "var(--border)";
            e.currentTarget.style.color = "var(--muted-foreground)";
          }}
        >
          <RotateCcw size={13} />
          New Brief
        </button>

        <div style={{ display: "flex", gap: "10px" }}>
          <button
            onClick={handleCopy}
            style={{
              display: "flex",
              alignItems: "center",
              gap: "8px",
              padding: "13px 22px",
              background: "transparent",
              border: "1px solid var(--border)",
              borderRadius: "3px",
              color: copied ? "var(--accent)" : "var(--foreground)",
              fontSize: "11px",
              fontWeight: 600,
              letterSpacing: "0.1em",
              textTransform: "uppercase",
              cursor: "pointer",
              transition: "all 0.2s ease",
              fontFamily: "var(--font-dm-sans), sans-serif",
            }}
          >
            {copied ? <Check size={13} /> : <Copy size={13} />}
            {copied ? "Copied!" : "Copy Brief"}
          </button>
          <button
            onClick={handleDownload}
            style={{
              display: "flex",
              alignItems: "center",
              gap: "8px",
              padding: "13px 28px",
              background: "var(--accent)",
              border: "1px solid var(--accent)",
              borderRadius: "3px",
              color: "var(--background)",
              fontSize: "11px",
              fontWeight: 700,
              letterSpacing: "0.14em",
              textTransform: "uppercase",
              cursor: "pointer",
              transition: "all 0.2s ease",
              fontFamily: "var(--font-dm-sans), sans-serif",
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.background = "var(--accent-light)";
              e.currentTarget.style.borderColor = "var(--accent-light)";
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.background = "var(--accent)";
              e.currentTarget.style.borderColor = "var(--accent)";
            }}
          >
            <Download size={13} />
            Download Brief
          </button>
        </div>
      </div>
    </div>
  );
}
